In [4]:
#pip install numpy
import numpy as np


In [15]:
import random
l=[random.randint(0,5),random.randint(0,5)]#m.randint()]
print(l)
ls=l
ls

[5, 2]


[5, 2]

In [13]:
al=np.array([1,2,3,4])

NameError: name 'np' is not defined

In [16]:
for num in range(3):
    print(random.randrange(100, 999, 5), end=', ')

730, 150, 905, 

In [7]:
print(al)

array([1, 2, 3, 4])

In [21]:
for num in range(3):
   print(random.randrange(0,6))

2
4
1


In [8]:
type(al)

numpy.ndarray

In [25]:
def main(x,y):
    #x,y =2,8
    
    if(x < y):
        st= "x is less than y"
    print(st)
    
#if __name__ == "__main__":
main(12,8)

UnboundLocalError: cannot access local variable 'st' where it is not associated with a value

In [25]:
arr=np.array(list)

In [27]:
c=0
while c<=5:
    #print(c)
    c+=1
    
Months = ["Jan","Feb","Mar","April","May","June"]
for i, m in enumerate (Months):
        print(i,m)

0 Jan
1 Feb
2 Mar
3 April
4 May
5 June


In [41]:
list=[4,5,6,7.5,'15']

In [33]:
for i in '173':
 print ("guru99",i)

guru99 1
guru99 7
guru99 3


In [26]:
print(arr)

['4' '5' '6' '7.5' 'sid']


In [34]:
Dict = {'Tim': 18,'Charlie':12,'Tiffany':22,'Robert':25}    
print("Students Name: %s" % list(Dict.items()))

Students Name: [('Tim', 18), ('Charlie', 12), ('Tiffany', 22), ('Robert', 25)]


In [35]:
Dict = {'Tim': 18,'Charlie':12,'Tiffany':22,'Robert':25}
Boys = {'Tim': 18,'Charlie':12,'Robert':25}
Girls = {'Tiffany':22}
Students = list(Dict.keys())
Students.sort()
for S in Students:
      print(":".join((S,str(Dict[S]))))

Charlie:12
Robert:25
Tiffany:22
Tim:18


In [45]:
from functools import cmp_to_key
Boys = {'Tim': 18,'Charlie':12,'Robert':25}
Girls = {'Tiffany':22}    
#print cmp(Girls, Boys)
Dict = {'Tim': 18,'Charlie':12,'Tiffany':22,'Robert':25}    
print("Length : %d" % len (Dict))

Length : 4


In [21]:
type(arr)

numpy.ndarray

In [42]:
ass=np.array(list,dtype="int")

In [37]:
type(ass)

numpy.ndarray

In [43]:
print(ass)

[ 4  5  6  7 15]


In [44]:
a1=np.arange(1,10)
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a2=np.arange(10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a3=np.arange(-10,15,2)
a3

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10,  12,  14])

In [55]:
random=np.random.rand(5,4)
print(random)

[[0.68397173 0.5035716  0.31498877 0.67454795]
 [0.85711528 0.51617457 0.42969223 0.46782743]
 [0.28667476 0.72611733 0.60974586 0.96440042]
 [0.41620982 0.31875272 0.79192987 0.09782407]
 [0.86714113 0.32486935 0.87054416 0.26255924]]


In [65]:
arr=np.random.randint(2,7,size=(8,16))
print(arr)

[[6 2 5 3 2 3 4 3 5 4 6 2 3 5 4 4]
 [5 2 6 4 5 5 6 6 5 6 2 4 4 3 2 2]
 [3 5 6 2 3 5 5 5 5 5 5 3 6 2 6 2]
 [3 4 4 5 5 3 5 5 5 3 3 2 6 6 6 5]
 [3 3 4 3 6 6 3 4 3 4 5 2 6 3 6 5]
 [5 6 6 6 2 6 2 2 5 4 3 6 2 2 2 3]
 [3 6 4 5 4 4 4 3 5 6 5 5 5 2 5 3]
 [3 3 5 5 5 4 3 3 2 2 4 3 2 4 4 6]]


In [66]:
zero=np.zeros(6,dtype=int)
zero

array([0, 0, 0, 0, 0, 0])

In [69]:
a=np.ones(10,dtype=int)
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [82]:
zero1=np.zeros(10,dtype=int).reshape(4,5)
zero1

ValueError: cannot reshape array of size 10 into shape (4,5)

In [83]:
arr=np.array([1,2,3,4,5,6]).reshape(3,2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [85]:
arr.ndim

2

In [86]:
arr.size

6

In [117]:
arr.shape

(3, 4)

In [87]:
len(arr)

3

In [88]:
s=arr.T
s

array([[1, 3, 5],
       [2, 4, 6]])

In [102]:
arr=np.array([[33,17,12,55],[65,32,84,43],[54,31,71,28]])
arr

array([[33, 17, 12, 55],
       [65, 32, 84, 43],
       [54, 31, 71, 28]])

In [103]:
arr[2]

array([54, 31, 71, 28])

In [110]:
arr[1:3]

array([[65, 32, 84, 43],
       [54, 31, 71, 28]])

In [122]:
arr[1:3,1:3]

array([[32, 84],
       [31, 71]])

In [131]:
arr[1:3,3:4]

array([[43],
       [28]])

In [132]:
arr[:]

array([[33, 17, 12, 55],
       [65, 32, 84, 43],
       [54, 31, 71, 28]])

In [133]:
import numpy as mp

In [134]:
a1=np.array([1,3,4,5,6])
print(a1)

[1 3 4 5 6]


In [135]:
type(a1)

numpy.ndarray

In [137]:
import os
os.getcwd()

'C:\\Users\\Siddhay'

In [139]:
a2=np.array([1,5,7,5.5,8,4],dtype='int')
print(a2)
type(a2)

[1 5 7 5 8 4]


numpy.ndarray

In [149]:
a3=np.arange(0,10)
a3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
a4=np.arange(10)
a4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
a5=np.arange(10,-10,-1)
a5

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0, -1, -2, -3, -4, -5, -6,
       -7, -8, -9])

random simulations

In [154]:
r1=np.random.rand(5,6)
r1

array([[0.44735365, 0.45129487, 0.13869193, 0.4362264 , 0.25631388,
        0.63096138],
       [0.27415117, 0.04766515, 0.25185582, 0.40169813, 0.86266912,
        0.10924693],
       [0.71052872, 0.95928569, 0.9107484 , 0.37839014, 0.0203895 ,
        0.50254592],
       [0.13765227, 0.77229807, 0.53059097, 0.69158429, 0.0459181 ,
        0.10506955],
       [0.38325797, 0.25063632, 0.69826177, 0.50505209, 0.420184  ,
        0.04386429]])

In [156]:
r2=np.random.randn(2,5)
r2

array([[ 0.5445326 ,  2.94960104, -0.76282874,  0.49378378,  2.17006947],
       [ 0.37541036, -0.38812831,  0.93919739,  0.29475475,  0.04544384]])

In [157]:
r3=np.random.ranf(3)
r3

array([0.36191681, 0.95127712, 0.57043363])

In [161]:
r4=np.random.randint(2,5,size=(2,8))
r4

array([[2, 2, 4, 4, 4, 4, 4, 3],
       [3, 4, 2, 2, 2, 3, 4, 4]])

In [162]:
r5=np.random.seed(5)##########3ask sir
r5

In [167]:
r6=np.array([1,2,3,'4.0',5])
print(r6)
type(r6)

['1' '2' '3' '4.0' '5']


numpy.ndarray

In [166]:
r7=np.array([1,2,3,4.4,5,6])
r7

array([1. , 2. , 3. , 4.4, 5. , 6. ])

In [169]:
zero=np.zeros(6,dtype="int").reshape(2,3)
zero

array([[0, 0, 0],
       [0, 0, 0]])

In [191]:
one=np.ones(10,dtype='int').reshape(2,5)
one 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [198]:
r2d=np.array([[2,3,4],[4,5,6],[5,6,7]])
nin=r2d[2][1]# call 6 from string
nin

6

In [208]:
d2r=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(d2r)
print("xxxxxxxxxxxxxxxxxxxxxxxxx")
arr=d2r[2]
arr
print(d2r.ndim)
print(d2r.size)
t=d2r.T
t

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
xxxxxxxxxxxxxxxxxxxxxxxxx
2
12


array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

indexing and slicing

In [210]:
in1=np.array([[33,17,12,55],[65,32,87,43],[54,31,77,28]])
print(in1)

[[33 17 12 55]
 [65 32 87 43]
 [54 31 77 28]]


In [216]:
in1[0,3]

55

In [220]:
in1[:,]

array([[33, 17, 12, 55],
       [65, 32, 87, 43],
       [54, 31, 77, 28]])

In [228]:
in1[1:,1:3]

array([[32, 87],
       [31, 77]])

In [232]:
in1[:1,2:3]

array([[12]])

In [233]:
in1[1:,:2]

array([[65, 32],
       [54, 31]])

In [234]:
in1[1,1:3]

array([32, 87])

In [235]:
print(in1)

[[33 17 12 55]
 [65 32 87 43]
 [54 31 77 28]]


In [236]:
in1[2,1:3]

array([31, 77])

In [239]:
in1[0:1,1:3]

array([[17, 12]])

In [242]:
in1[:,1:3][:,1]

array([12, 87, 77])

In [243]:
in1[:,1]

array([17, 32, 31])

In [244]:
in1

array([[33, 17, 12, 55],
       [65, 32, 87, 43],
       [54, 31, 77, 28]])

In [245]:
in1[1:,1:]

array([[32, 87, 43],
       [31, 77, 28]])

In [246]:
in1[1:,0:2]

array([[65, 32],
       [54, 31]])

In [251]:
in2=np.array([12   ,13,14,15,29,43,32,21])
print(in2)
print(in2>17) # boolean indexing

[12 13 14 15 29 43 32 21]
[False False False False  True  True  True  True]


broadcasting

In [259]:
b=np.array([10,12,14,16,18,20])
b1=b*10
print(b1)
b2=b1/2
print(b2)

[100 120 140 160 180 200]
[ 50.  60.  70.  80.  90. 100.]


reshaping

In [265]:
re=np.array([0,11,1,2,3,4,5,6,7,8,9,10])
re.reshape(6,2)

array([[ 0, 11],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [266]:
ar=np.arange(10,20).reshape(5,2)
ar

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [267]:
ar.sum()

145

In [268]:
ar.sum(axis=0)

array([70, 75])

In [269]:
ar.sum(axis=1)

array([21, 25, 29, 33, 37])

In [275]:
a1=np.arange(1,9).reshape(2,4)
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [282]:
a2=np.arange(10,18).reshape(2,4)
a2

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [283]:
a=a2.T
a

array([[10, 14],
       [11, 15],
       [12, 16],
       [13, 17]])

In [284]:
a3=np.concatenate((a1,a2))
a3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [287]:
app=a1+a2

In [288]:
app

array([[11, 13, 15, 17],
       [19, 21, 23, 25]])

In [6]:
a1=np.array([[2,3,-1],[-6,0,4]])
a1

array([[ 2,  3, -1],
       [-6,  0,  4]])

In [7]:
a1[1][2]

4

In [10]:
a1[1:,2:]

array([[4]])

In [11]:
a2=np.array([[-1,45,38],[7,12,9]])
a2

array([[-1, 45, 38],
       [ 7, 12,  9]])

In [12]:
a2[0][1]

45

In [13]:
a2[0:2,0:2]

array([[-1, 45],
       [ 7, 12]])

In [16]:
a2[0,1]

45

In [17]:
a3=a2.T
a3

array([[-1,  7],
       [45, 12],
       [38,  9]])

In [20]:
a4=np.arange(6)
a4

array([0, 1, 2, 3, 4, 5])

In [21]:
a5=a4*2
a5

array([ 0,  2,  4,  6,  8, 10])

In [22]:
arr=np.arange(1,19).reshape(3,6)
arr

array_1=arr[0:3,2:5]

array_2=arr[1:4,1:4]

print(array_1)
print(array_2)


[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]]
[[ 8  9 10]
 [14 15 16]]


In [29]:
no=[1,2,3,4,5,6,7,8,9,10]
f=filter(lambda x:x%2==0,no)
even=list(f)
even

[2, 4, 6, 8, 10]

In [31]:
f=filter(lambda y:y%2!=0,no)
odd=list(f)
odd

[1, 3, 5, 7, 9]

In [38]:
def factorial(n):
    if n==0:
        return 1
    else:
        return n * factorial(n-1)
    
num = int(input("Enter the number: "))
result=factorial(num)
print(f"the final result {num} is : {result}")

Enter the number: 4
the final result 4 is : 24


In [40]:
x=lambda y:y**2
print(x(8))

64


In [43]:
y=int(input('enter your number : '))

x=y**2
print(x)

enter your number : 8
64


In [45]:
x=lambda a,b:a+b
print(x(5,7))

12


In [46]:
l=[2,10,9,56,53,83,16]
print("the list is : ",l)
x=list(filter(lambda a:a%2==0,l))
print(f"the even number from the strings are :{x}")

the list is :  [2, 10, 9, 56, 53, 83, 16]
the even number from the strings are :[2, 10, 56, 16]


In [53]:
num = int(input("enter the number: "))
def factorial(n):
    if n==0:
        return 1
    
    return n * factorial(n-1)
    
result=factorial(num)
print(f"the factorial of {num} is: {result}")

enter the number: 5
the factorial of 5 is: 120


In [9]:
arr=np.array(50)
arr
arr.dtype()

TypeError: 'numpy.dtype[int32]' object is not callable

In [12]:
arr=np.arange(20)
arr
arr.dtype

dtype('int32')

In [15]:
import numpy as np
arr=np.array([20,21,22,23])
arr.astype(float)

array([20., 21., 22., 23.])

In [18]:
import numpy as np
dict={'a':1,'b':2,'c':3}
dict1=np.array(list(dict.values()))


dict2=np.asarray(list(dict.values()))
print(dict1)
print(dict2)

[1 2 3]
[1 2 3]


In [20]:
import numpy as np

# Sample dictionary
my_dict = {'a': 1, 'b': 2, 'c': 3}

# Using numpy.array
array_from_dict1 = np.array(list(my_dict.values()))

# Using numpy.asarray
array_from_dict2 = np.asarray(list(my_dict.values()))

print("NumPy array from dictionary (using array method):", array_from_dict1)
print("NumPy array from dictionary (using asarray method):", array_from_dict2)

NumPy array from dictionary (using array method): [1 2 3]
NumPy array from dictionary (using asarray method): [1 2 3]


In [23]:
import pandas as pd
df = pd.DataFrame({'Column_Name': ['A', 'B', 'A', 'C', 'B', 'A']})
counts = df['Column_Name'].value_counts()
print(counts)

Column_Name
A    3
B    2
C    1
Name: count, dtype: int64


In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {'Column_Name': ['A', 'B', 'A', 'C', 'B', 'A']}
df = pd.DataFrame(data)

# Get frequency counts of unique items in the specified column
frequency_counts = df['Column_Name'].value_counts()

# Display the result
print(frequency_counts)